language: python
matrix:
  include:
    - python: 3.7.2
      dist: xenial
      sudo: true
before_install:
    - pip install --upgrade setuptools pip
    - pip install -r requirements.txt
    - pip install coveralls
script:
  - python manage.py test -v2
  - coverage run --omit="manage.py" --source="api_fintech/" --source="calculator/" manage.py test -v2
after_success:
  - coveralls
