language: python
matrix:
  include:
    - python: 3.7.2
      dist: xenial
      sudo: true
before_install:
    - pip install --upgrade setuptools pip
    - pip install -r requirements.txt
script:
  - python manage.py test -v2
