# Generated by Django 2.0.7 on 2019-05-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.FloatField(),
        ),
    ]
