# Generated by Django 2.2.1 on 2019-05-20 20:18

import calculator.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='rate_adjust',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Adjustment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_expected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.CharField(default=calculator.models.increment_loan_id, editable=False, max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='instalment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Instalment'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('made', 'made'), ('missed', 'missed')], db_column='type', max_length=6, verbose_name='status'),
        ),
    ]
