# Generated by Django 2.2.1 on 2019-05-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('made', 'made'), ('missed', 'missed')], max_length=2, verbose_name='Type'),
        ),
    ]
