# Generated by Django 2.2.1 on 2019-05-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Client'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.IntegerField(verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Loan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('MD', 'Made'), ('MS', 'Missed')], db_column='type', default='MD', max_length=2, verbose_name='Type'),
        ),
    ]
