# Generated by Django 2.2.1 on 2019-05-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20190505_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='loan_id',
            field=models.TextField(choices=[('1', '1'), ('2', '2')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid',
            field=models.TextField(choices=[('missed', 'missed'), ('made', 'made')]),
        ),
    ]
