# Generated by Django 2.2.1 on 2019-05-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20190514_0107'),
        ('calculator', '0002_auto_20190513_0213'),
    ]

    operations = [
    ]
