# Generated by Django 2.2.1 on 2019-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='paid',
            field=models.CharField(choices=[('missed', 'Missed'), ('made', 'Made')], max_length=6),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
