# Generated by Django 2.2.1 on 2019-05-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20190518_0120'),
        ('calculator', '0003_merge_20190514_0221'),
    ]

    operations = [
    ]
