# Generated by Django 2.2.1 on 2019-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20190505_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='loan_id',
            field=models.ForeignKey(on_delete='PROTECT', to='calculator.Loans'),
        ),
    ]
